FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt update && apt upgrade -y && apt install -y --no-install-recommends \
    ca-certificates curl jq git iputils-ping libcurl4 libunwind8 netcat bash-completion \
    apt-transport-https lsb-release \
    wget vim zip unzip gnupg \
    gnupg-agent software-properties-common

# PowerShell Core
RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt update && apt install -y powershell && \
    rm packages-microsoft-prod.deb

# Reading versions from versions.jsonc
COPY versions.jsonc .

# terraform
RUN wget https://releases.hashicorp.com/terraform/$(jq .versions.terraform versions.jsonc -r)/terraform_$(jq .versions.terraform versions.jsonc -r)_linux_amd64.zip && \
    unzip terraform_$(jq .versions.terraform versions.jsonc -r)_linux_amd64.zip -d /usr/local/bin/ && \
    rm terraform_$(jq .versions.terraform versions.jsonc -r)_linux_amd64.zip

# kubectl
RUN curl -L https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl && \
    chmod +x /usr/local/bin/kubectl

# helm
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# az cli
RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.asc.gpg > /dev/null && \
    AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list && \
    apt update && apt install azure-cli

# tflint
RUN curl -sSL -o /tmp/tflint.zip https://github.com/terraform-linters/tflint/releases/download/$(jq .versions.tfLint versions.jsonc -r)/tflint_linux_amd64.zip && \
    unzip -d /usr/bin /tmp/tflint.zip && \
    chmod +x /usr/bin/tflint && \
    rm /tmp/tflint.zip

# tflint azurerm plugin
RUN curl -sSL -o /tmp/tflint-ruleset-azurerm_linux_amd64.zip https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/$(jq .versions.tfLintAzureRules versions.jsonc -r)/tflint-ruleset-azurerm_linux_amd64.zip && \
    mkdir --parents /root/.tflint.d/plugins && \
    unzip -d /root/.tflint.d/plugins /tmp/tflint-ruleset-azurerm_linux_amd64.zip && \
    echo "plugin \"azurerm\" { enabled = true }" > /root/.tflint.hcl && \
    rm /tmp/tflint-ruleset-azurerm_linux_amd64.zip

# tfsec
RUN curl -sSL -o /usr/bin/tfsec https://github.com/liamg/tfsec/releases/download/$(jq .versions.tfSec versions.jsonc -r)/tfsec-linux-amd64 && \
    chmod +x /usr/bin/tfsec

# Enable bash completion
RUN echo '. /etc/bash_completion' >> ~/.bashrc